### ISSUE TITLE
Adding Covid information in FAQ

### ISSUE THREAD

**Issue by andreicozma1** [volhacks/volhacks.github.io#82]
You'd work on this with @hunterprice04 and also Luis and Liliane.

Please write down any updates or questions for me and hunter here in the comments throughout development

**Comment by Manan-dev** [comment]
I suggest we prepare a FAQ but not post it till we get "confirmed" announcement from Donde because In the email she said that they will reevaluate soon

**Comment by andreicozma1** [comment]
Sounds great to me! Let's work with Hunter, Luis, and Liliane on what to add to the FAQ and we'll keep this updated

**Comment by Manan-dev** [comment]
add a link on landing page

**Comment by hunterprice04** [comment]
title - "COVID-19 info" or "Hybrid Event Details" or ideas?
blurb - "Due to the uncertainty of the development of COVID-19, we will be offering both in-person and virtual options for this year's event. For those who are attending in person, we will be implementing the Federal, State, and Local COVID-19 Guidelines at the time of the event to maintain the health and safety of the other participants. These guidelines include but are not limited to required masks at all times while within the premises and enforced social distancing. If you are feeling sick or have been recently exposed to someone who has COVID-19, we ask you to please attend the event virtually."

if someone has Grammarly pro can you check the tone

**Comment by andreicozma1** [comment]
Corrected with grammarly:
"Due to the uncertainty of the development of COVID-19, we will be offering both in-person and virtual options for this year's event. For those attending in person, we will be implementing the Federal, State, and Local COVID-19 Guidelines at the time of the event to maintain the health and safety of the other participants. These guidelines include but are not limited to required masks at all times while within the premises and enforced social distancing. If you feel sick or have been recently exposed to someone who has COVID-19, we ask you to please attend the event virtually."

Also what about the landing page short tex? @hunterprice04 @Manan-dev

**Comment by andreicozma1** [comment]
I like Hybrid Event Details

**Comment by andreicozma1** [comment]
Todo: 

Move Hybrid Event Details card to top right of FAQ (to the right of What is a Hackathon)
The "Is there a code of conduct?" Should be put right under the Hybrid Event Details card.
The "Is there a hardware lab" card and the rest should follow under
